config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'photos#index'
  resources :photos do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @gender = Gender.find([2, 3, 4])
    @price = Price.find([2, 3, 4, 5, 6])
    @tags = Tag.all.order('created_at DESC')
    @value = params['search']['value']
    @how = params['search']['how']
    @datas = search_for(@how, @value)
  end

  private

  def match_gender(value)
    Photo.where(gender_id: value)
  end

  def match_price(value)
    Photo.where(price_id: value)
  end

  def match_tag(value)
    Photo.where(id: PhotoTag.select(:photo_id)
    .where(tag_id: value)
    .group(:photo_id))
  end

  def keyword(value)
    Photo.where('title LIKE(?) OR description LIKE(?)', "%#{value}%", "%#{value}%")
  end

  def search_for(how, value)
    case how
    when 'match_gender'
      match_gender(value)
    when 'match_price'
      match_price(value)
    when 'match_tag'
      match_tag(value)
    else
      keyword(value)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<body class="sb-nav-fixed">
    <%= render 'shared/header' %> 
    <div id="layoutSidenav">
        <%= render 'shared/side_nav' %> 
        <div id="layoutSidenav_content">
            <header class="bg-secondary py-5">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="text-center text-black">
                        <h1 class="display-4 fw-bolder">Fashion Tweet</h1>
                        <p class="lead fw-normal text-black-50 mb-0">Baby, Kids向けトータルファッションサイト</p>
                    </div>
                </div>
            </header>
            <main>
                <section class="py-5">
                    <div class="pick-up-slide text-center">
                        <h1 class="display-5 text-black-50 mb-0">Results</h1>
                    </div>
                    <div class="container px-4 px-lg-5 mt-5">
                        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                            <% @datas.each do |data|%>
                              <div class="col mb-5">
                                  <div class="card", style="height: 376px;">
                                      <%= image_tag data.snap, class: "card-img-top", style: "height: 159px;" %>
                                      <div class="card-body p-4">
                                          <div class="text-center">
                                              <h5 class="fw-bolder"><%= data.title %></h5>
                                              <div>
                                                  <% data.photo_tags.each do |tag|%>
                                                      <span>#<%= tag.tag.name %></span>
                                                  <% end %>
                                              </div>
                                              <%=link_to data.user.nickname, user_path(data.user.id), style: "text-decoration: none; color: black;" %>
                                          </div>
                                      </div>
                                      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                          <div class="text-center"><%=link_to "詳細", photo_path(data.id), class:"btn btn-outline-dark mt-auto" %></div>
                                      </div>
                                  </div>
                              </div>
                            <% end %>
                        </div>
                    </div>
                </section>
            </main>
            <%= render 'shared/footer' %> 
        </div>
    </div>
</body>