config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'photos#index'
  resources :photos do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :photos, dependent: :destroy
  has_many :comments
  has_many :sns_credentials
  
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns } 
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, on: :create

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ーa-zA-Z]+\z/ } do
    validates :last_name
    validates :first_name
  end

  validates :nickname, presence: true

  validates :introduction, length: { maximum: 200 }
  has_one_attached :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

 def authorization
  sns_info = User.from_omniauth(request.env["omniauth.auth"])
  @user = sns_info[:user]

  if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
    sign_in_and_redirect @user, event: :authentication
  else #ユーザー情報が未登録なので、新規登録画面へ遷移する
    @sns_id = sns_info[:sns].id
    render template: 'devise/registrations/new'
  end
 end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:edit, :update]

  def show
    @photos = @user.photos.order('created_at DESC')
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :profile_image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index
    redirect_to root_path and return unless user_signed_in?

    redirect_to root_path unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body class="sb-nav-fixed">
    <%= render 'shared/header' %> 
        <div id="layoutSidenav_content">
            <main>
                <section class="py-5">
                    <div class="pick-up-slide text-center">
                        <h1 class="display-6 text-dark mb-3">マイページ情報を編集する</h1>
                    </div>
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                      <div class="border col-7">
                          <div class="row">
                              <div class="col-md">
                                  <%= form_with model: current_user, local: true do |f| %>
                                  <%= render 'shared/error_messages', model: f.object %>
                                      <br>
                                      <div class="form-group">
                                          <%= f.label :nickname, "Nickname 必須" %>
                                          <%= f.text_field :nickname, class: "form-control" %>
                                      </div>
                                      <br>
                                      <!--<div class="form-group">
                                          <%= f.label :password, "password 必須" %>
                                          <%= f.password_field :password, class: "form-control" %>
                                      </div>
                                      <br>
                                      <div class="form-group">
                                          <%= f.label :password_confirmation, "password_confirmation 必須" %>
                                          <%= f.password_field :password_confirmation, class: "form-control" %>
                                      </div>
                                      <br>-->
                                      <div class="form-group">
                                          <%= f.label :email, "Email 必須" %>
                                          <%= f.email_field :email, class: "form-control", autofocus: true, autocomplete: "email" %>
                                      </div>
                                      <br>
                                      <div class="form-group">
                                          <%= f.label :profile_image, "プロフィール画像" %>
                                          <%= f.file_field :profile_image, accept: "image/jpeg, image/png" %>
                                      </div>
                                      <br>
                                      <div class="form-group">
                                          <%= f.label :introduction, "自己紹介" %>
                                          <%= f.text_area :introduction, class: "form-control", rows: "3" %>
                                      </div>
                              </div>
                          </div>
                          <br>
                          <div class="row center-block text-center">
                              <div class="col-1">
                              </div>
                              <div class="col-5">
                                  <%=link_to "戻る", user_path(current_user.id), class:"btn btn-outline-secondary btn-block" %>
                              </div>
                              <div class="col-5">
                                  <%= f.submit "更新する", class:"btn btn-outline-primary btn-block" %>
                              </div>
                          </div>
                          <% end %>
                          <br>
                      </div>
                    </div>
                </section>
            </main>
            <%= render 'shared/footer' %> 
        </div>
    </div>
</body>

app/views/users/show.html.erb
<body class="sb-nav-fixed">
  <%= render 'shared/header' %> 
  <header class="bg-secondary py-5">
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
      <!-- Heading Row-->
      <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
          <% unless @user.profile_image.blank? %>
            <%= image_tag @user.profile_image, class: "img-fluid rounded mb-4 mb-lg-0" %>
          <% else %>
            <%= image_tag "https://dummyimage.com/900x400/dee2e6/6c757d.jpg", class: "img-fluid rounded mb-4 mb-lg-0" %>
          <% end %>
        </div>
        <div class="col-lg-5">
          <% if @user == current_user && user_signed_in? %>
            <%= link_to "編集", edit_user_path(@user.id), class: "btn btn-primary" %>
          <% end %>
          <h1 class="font-weight-light"><%= @user.nickname %></h1>
          <h2 class="font-weight-light">プロフィール</h2>
          <p><%= @user.introduction %></p>
        </div>
      </div>
    </div>
  </header>
  <main>
    <section class="py-5">
      <div class="pick-up-slide text-center">
          <h1 class="display-5 text-black-50 mb-0">Gallery</h1>
          <% if @user == current_user && user_signed_in? %>
            <%=link_to "投稿", new_photo_path, class:"btn btn-primary" %>
          <% end %>
      </div>
         <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <% unless @photos.empty? %>
                    <%= render partial: "photos/photo", collection: @photos %>
                <% else %>
                    <div class="col mb-5">
                        <div class="card", style="height: 376px;">
                            <%= image_tag "https://dummyimage.com/450x300/dee2e6/6c757d.jpg", class: "card-img-top", style: "height: 159px;" %>
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">投稿してください</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </section>
  </main>
  <%= render 'shared/footer' %> 
  </div>
</body>