config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'photos#index'
  resources :photos do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :text, presence: true, length: { maximum: 100 }
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'Baby' },
    { id: 3, name: 'Boy' },
    { id: 4, name: 'Girl' }
  ]

  include ActiveHash::Associations
  has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :price
  belongs_to :gender
  belongs_to :user
  has_many :photo_tags, dependent: :destroy
  has_many :tags, through: :photo_tags
  has_many :comments, dependent: :destroy

  has_one_attached :snap
  validates :snap, presence: true
  validates :title, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 500 }
  with_options presence: true, numericality: { other_than: 1, message: 'Select' } do
    validates :price_id
    validates :gender_id
  end
end

app/models/photo_tag.rb
class PhotoTag < ApplicationRecord
  belongs_to :photo
  belongs_to :tag
end

app/models/price.rb
class Price < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '0〜1500円' },
    { id: 3, name: '1500〜5000円' },
    { id: 4, name: '5000〜10000円' },
    { id: 5, name: '10000〜20000円' },
    { id: 6, name: '20000円以上' }
  ]

  include ActiveHash::Associations
  has_many :photos
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :photo_tags, dependent: :destroy
  has_many :photos, through: :photo_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :photos, dependent: :destroy
  has_many :comments
  has_many :sns_credentials
  
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns } 
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, on: :create

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ーa-zA-Z]+\z/ } do
    validates :last_name
    validates :first_name
  end

  validates :nickname, presence: true

  validates :introduction, length: { maximum: 200 }
  has_one_attached :profile_image
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: :destroy
  before_action :move_to_referer, only: :destroy

  def create
    comment = Comment.create(comment_params)
    redirect_to "/photos/#{comment.photo.id}"
  end

  def destroy
    @comment.destroy
    redirect_to request.referer
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, photo_id: params[:photo_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def move_to_referer
    redirect_to request.referer and return unless user_signed_in?

    redirect_to request.referer unless @comment.user == current_user
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: :index
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.includes(:user).order('created_at DESC')
    @random = Photo.order('RAND()').limit(6)
    @gender = Gender.find([2, 3, 4])
    @price = Price.find([2, 3, 4, 5, 6])
  end

  def new
    @photo = Photo.new
    @photo.photo_tags.build
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.valid?
      @photo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @photo_tags = @photo.photo_tags.order('created_at DESC')
    @comment = Comment.new
    @comments = @photo.comments.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to photo_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to root_path
  end

  private

  def photo_params
    params.require(:photo).permit(:snap, :title, :gender_id, :price_id, :description,
                                  { tag_ids: [] }).merge(user_id: current_user.id)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def set_tags
    @tags = Tag.all.order('created_at DESC')
  end

  def move_to_index
    redirect_to root_path and return unless user_signed_in?

    redirect_to root_path unless @photo.user == current_user
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @gender = Gender.find([2, 3, 4])
    @price = Price.find([2, 3, 4, 5, 6])
    @tags = Tag.all.order('created_at DESC')
    @value = params['search']['value']
    @how = params['search']['how']
    @datas = search_for(@how, @value)
  end

  private

  def match_gender(value)
    Photo.where(gender_id: value)
  end

  def match_price(value)
    Photo.where(price_id: value)
  end

  def match_tag(value)
    Photo.where(id: PhotoTag.select(:photo_id)
    .where(tag_id: value)
    .group(:photo_id))
  end

  def keyword(value)
    Photo.where('title LIKE(?) OR description LIKE(?)', "%#{value}%", "%#{value}%")
  end

  def search_for(how, value)
    case how
    when 'match_gender'
      match_gender(value)
    when 'match_price'
      match_price(value)
    when 'match_tag'
      match_tag(value)
    else
      keyword(value)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    session[:previous_url] = request.referer
    @tag = Tag.new
  end

  def create
    @session = session[:previous_url]
    @tag = Tag.create(tag_params)
    if @tag.save
      redirect_to @session
    else
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:edit, :update]

  def show
    @photos = @user.photos.order('created_at DESC')
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :profile_image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index
    redirect_to root_path and return unless user_signed_in?

    redirect_to root_path unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionTweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="app/assets/stylesheets/styles.css" rel="stylesheet" />
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
    <!-- Bootstrap core JavaScript-->
    <script src="jquery.min.js" type="text/javascript"></script>
    <script src="bundle.min.js" type="text/javascript"></script>

    <!-- Core plugin JavaScript-->
    <script src="jquery.easing.min.js" type="text/javascript"></script>

    <!-- Custom scripts for all pages-->
    <script src="sb-admin-2.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous" type="text/javascript"></script>
    <script src="./app/javascript/scripts.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" type="text/javascript"></script>

    <!-- slick -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/> 
    <link rel="stylesheet" href="app/assets/stylesheets/slick-theme.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>
    <script src="slick.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript">
        $(document).on('ready', function() {
          $(".regular").slick({
            dots: true,
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3
          });
        });
    </script>

    <!-- select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" type="text/javascript"></script>
      <script type="text/javascript">
        $(document).ready(function() {
        $('.js-example-basic-multiple').select2();
        });
    </script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; FashionTweet 2021</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <li><%= link_to "LOGO", root_path, class: "navbar-brand ps-3" %></li>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <%= form_with(url: search_search_path, local: true, method: :get, class: "d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0") do |form| %>
        <div class="input-group">
            <%= form.text_field 'search[value]', placeholder: "キーワードで検索", class: "form-control", 'search[how]': "keyword" %>
            <%= form.submit "検索", class: "btn btn-primary", id: "btnNavbarSearch" %>
        </div>
    <% end %>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <% if user_signed_in? %>
                    <li><%= link_to current_user.nickname, user_path(current_user.id), class: "dropdown-item" %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                <% else %>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "dropdown-item" %></li>
                    <li><%= link_to '新規登録', new_user_registration_path, class: "dropdown-item" %></li>
                <% end %>
            </ul>
        </li>
    </ul>
</nav>

app/views/shared/_side_nav.html.erb
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">探す</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseGender" aria-expanded="false" aria-controls="collapseGender">
                    ジャンルで探す
                </a>
                <div class="collapse" id="collapseGender" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <% @gender.each do |gender|%>
                            <%=link_to gender.name, search_search_path('search[value]': gender.id, 'search[how]': "match_gender"), class:"nav-link" %>
                        <% end %>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePrices" aria-expanded="false" aria-controls="collapsePrices">
                    値段で探す
                </a>
                <div class="collapse" id="collapsePrices" aria-labelledby="headingThree" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                       <% @price.each do |price|%>
                            <%=link_to price.name, search_search_path('search[value]': price.id, 'search[how]': "match_price"), class:"nav-link" %>
                        <% end %>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseSites" aria-expanded="false" aria-controls="collapseSites">
                    外部サイトから探す
                </a>
                <div class="collapse" id="collapseSites" aria-labelledby="headingThree" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseLowPrices" aria-expanded="false" aria-controls="pagesCollapseLowPrices">
                            安い・プチプラ系
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseLowPrices" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <%= link_to 'GU', "https://www.gu-global.com/jp", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'UNIQLO', "https://www.uniqlo.com/jp", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to '無印良品', "https://www.muji.com/jp/ja/store", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'GAP', "https://www.gap.co.jp/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'Zara', "https://www.zara.com/jp/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'H&M', "https://www2.hm.com/ja_jp/index.html", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'BELLE MAISON', "https://www.bellemaison.jp/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'ampersand', "https://fo-online.jp/shop/fokidsmart/ampersand", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to '西松屋', "https://shop-list.com/kids/brand/nishimatsuya/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'アカチャンホンポ', "https://akachan.omni7.jp/top", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseHighPrice" aria-expanded="false" aria-controls="pagesCollapseHighPrice">
                            高級・ハイブランド系
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseHighPrice" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <%= link_to 'GUCCI', "https://www.gucci.com/jp", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'ARMANI', "https://www.armani.com/jp", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'FENDI', "https://www.fendi.com/jp", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'Burberry', "https://jp.burberry.com/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'Stella McCartney', "https://www.stellamccartney.com/jp/ja/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                                <%= link_to 'baby Dior', "https://www.dior.com/ja_jp/", target: :_blank, rel: "noopener noreferrer", class:"nav-link" %>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">タグ</div>
                    <% @tags.each do |tag|%>
                        <%=link_to "##{tag.name}", search_search_path('search[value]': tag.id, 'search[how]': "match_tag") , class:"nav-link" %>
                    <% end %>
            </div>
            <div class="sb-sidenav-footer">
                <% if user_signed_in? %>
                    <div class="small">Logged in as:</div>
                        <%= current_user.nickname %>
                <% else %>
                    You are not logged in.
                <% end %>
            </div>
        </div>    
    </nav>
</div>