config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'photos#index'
  resources :photos do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :price
  belongs_to :gender
  belongs_to :user
  has_many :photo_tags, dependent: :destroy
  has_many :tags, through: :photo_tags
  has_many :comments, dependent: :destroy

  has_one_attached :snap
  validates :snap, presence: true
  validates :title, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 500 }
  with_options presence: true, numericality: { other_than: 1, message: 'Select' } do
    validates :price_id
    validates :gender_id
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: :index
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.includes(:user).order('created_at DESC')
    @random = Photo.order('RAND()').limit(6)
    @gender = Gender.find([2, 3, 4])
    @price = Price.find([2, 3, 4, 5, 6])
  end

  def new
    @photo = Photo.new
    @photo.photo_tags.build
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.valid?
      @photo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @photo_tags = @photo.photo_tags.order('created_at DESC')
    @comment = Comment.new
    @comments = @photo.comments.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to photo_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to root_path
  end

  private

  def photo_params
    params.require(:photo).permit(:snap, :title, :gender_id, :price_id, :description,
                                  { tag_ids: [] }).merge(user_id: current_user.id)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def set_tags
    @tags = Tag.all.order('created_at DESC')
  end

  def move_to_index
    redirect_to root_path and return unless user_signed_in?

    redirect_to root_path unless @photo.user == current_user
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_photo.html.erb
<div class="col mb-5">
    <div class="card", style="height: 376px;">
        <%= image_tag photo.snap, class: "card-img-top", style: "height: 159px;" %>
        <div class="card-body p-4">
            <div class="text-center">
                <h5 class="fw-bolder"><%= photo.title %></h5>
                <div>
                    <% photo.photo_tags.each do |tag|%>
                        <span>#<%= tag.tag.name %></span>
                    <% end %>
                </div>
                <%=link_to photo.user.nickname, user_path(photo.user.id), style: "text-decoration: none; color: black;" %>
            </div>
        </div>
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><%=link_to "詳細", photo_path(photo.id), class:"btn btn-outline-dark mt-auto" %></div>
        </div>
    </div>
</div>

app/views/photos/edit.html.erb
<body class="sb-nav-fixed">
  <%= render 'shared/header' %> 
      <div id="layoutSidenav_content">
          <main>
              <section class="py-5">
                  <div class="pick-up-slide text-center">
                      <h1 class="display-6 text-dark mb-3">投稿内容を編集する</h1>
                  </div>
                  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="border col-7">
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <%= form_with model: @photo, url: photo_path, local: true do |f| %>
                                <%= render 'shared/error_messages', model: f.object %>
                                    <div class="form-group">
                                        <%= f.label :snap, "画像 必須" %>
                                        <%= f.file_field :snap, accept: "image/jpeg, image/png" %>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <%= f.label :title, "コーディネートのタイトル 必須" %>
                                        <%= f.text_field :title, class: "form-control", placeholder: "" %>
                                    </div>
                                    <div class="form-group">
                                    <%= f.label :names, "タグ" %>
                                    <div class="col-5">
                                      <%=link_to '新規登録', new_tag_path, class:"btn btn-primary btn-block" %>
                                    </div>
                                    <%= f.collection_select(:tag_ids, Tag.all, :id, :name, {}, {class:"form-control js-example-basic-multiple",multiple: true, include_hidden: false}) %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :gender_id, "ジャンル" %>
                                        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control"}) %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :price_id, "Total金額" %>
                                        <%= f.collection_select(:price_id, Price.all, :id, :name, {}, {class:"form-control"}) %>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <%= f.label :description, "詳細コメント 必須" %>
                                        <%= f.text_area :description, class: "form-control", rows: "3" %>
                                    </div>
                                    <br>
                                    <div class="row center-block text-center">
                                        <div class="col-1">
                                        </div>
                                        <div class="col-5">
                                            <%=link_to '戻る', photo_path(@photo.id), class:"btn btn-outline-secondary btn-block" %>
                                        </div>
                                        <div class="col-5">
                                            <%= f.submit "更新する", class:"btn btn-outline-primary btn-block" %>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                        <br>
                    </div>
                  </div>
              </section>
          </main>
          <%= render 'shared/footer' %> 
      </div>
  </div>
</body>

app/views/photos/index.html.erb
<body class="sb-nav-fixed">
    <%= render 'shared/header' %> 
    <div id="layoutSidenav">
        <%= render 'shared/side_nav' %> 
        <div id="layoutSidenav_content">
            <header class="bg-secondary py-5">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="text-center text-black">
                        <h1 class="display-4 fw-bolder">Fashion Tweet</h1>
                        <p class="lead fw-normal text-black-50 mb-0">Baby, Kids向けトータルファッションサイト</p>
                        <div class="pick-up-slide">
                            <h1 class="display-5 text-black-50 mb-0">Pick Up</h1>
                        </div>
                        <section class="regular slider">
                            <% unless @photos.empty?%>
                                <% @random.each do |photo| %>
                                    <div>
                                        <%= image_tag photo.snap %>
                                    </div>
                                <% end %>
                            <% else %>
                                <div>
                                  <img src="http://placehold.it/350x300?text=1">
                                </div>
                                <div>
                                  <img src="http://placehold.it/350x300?text=2">
                                </div>
                                <div>
                                  <img src="http://placehold.it/350x300?text=3">
                                </div>
                                <div>
                                  <img src="http://placehold.it/350x300?text=4">
                                </div>
                                <div>
                                  <img src="http://placehold.it/350x300?text=5">
                                </div>
                                <div>
                                  <img src="http://placehold.it/350x300?text=6">
                                </div>
                            <% end %>
                        </section>
                    </div>
                </div>
            </header>
            <main>
                <section class="py-5">
                    <div class="pick-up-slide text-center">
                        <h1 class="display-5 text-black-50 mb-0">Gallery</h1>
                        <%=link_to "投稿", new_photo_path, class:"btn btn-primary" %>
                    </div>
                    <div class="container px-4 px-lg-5 mt-5">
                        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                            <% unless @photos.empty? %>
                                <%= render partial: "photo", collection: @photos %>
                            <% else %>
                                <div class="col mb-5">
                                    <div class="card", style="height: 376px;">
                                        <!-- Product image-->
                                        <img class="card-img-top" style="height: 159px;" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                                        <!-- Product details-->
                                        <div class="card-body p-4">
                                            <div class="text-center">
                                                <!-- Product name-->
                                                <h5 class="fw-bolder">投稿してください</h5>
                                                <!-- Product price-->
                                                ログインしてください
                                            </div>
                                        </div>
                                        <!-- Product actions-->
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </section>
            </main>
            <%= render 'shared/footer' %> 
        </div>
    </div>
</body>

app/views/photos/new.html.erb
<body class="sb-nav-fixed">
  <%= render 'shared/header' %> 
      <div id="layoutSidenav_content">
          <main>
              <section class="py-5">
                  <div class="pick-up-slide text-center">
                      <h1 class="display-6 text-dark mb-3">投稿内容を入力する</h1>
                  </div>
                  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="border col-7">
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <%= form_with model: @photo, url: photos_path, local: true do |f| %>
                                <%= render 'shared/error_messages', model: f.object %>
                                    <div class="form-group">
                                        <%= f.label :snap, "画像 必須" %>
                                        <%= f.file_field :snap, accept: "image/jpeg, image/png" %>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <%= f.label :title, "コーディネートのタイトル 必須" %>
                                        <%= f.text_field :title, class: "form-control", placeholder: "" %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :names, "タグ" %>
                                        <div class="col-5">
                                            <%=link_to '新規登録', new_tag_path, class:"btn btn-primary btn-block" %>
                                        </div>
                                        <%= f.collection_select(:tag_ids, Tag.all, :id, :name, {}, {class:"form-control js-example-basic-multiple",multiple: true, include_hidden: false}) %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :gender_id, "ジャンル" %>
                                        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control"}) %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :price_id, "Total金額" %>
                                        <%= f.collection_select(:price_id, Price.all, :id, :name, {}, {class:"form-control"}) %>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <%= f.label :description, "詳細コメント 必須" %>
                                        <%= f.text_area :description, class: "form-control", rows: "3" %>
                                    </div>
                                    <br>
                                    <div class="row center-block text-center">
                                        <div class="col-1">
                                        </div>
                                        <div class="col-5">
                                            <%=link_to '戻る', root_path, class:"btn btn-outline-secondary btn-block" %>
                                        </div>
                                        <div class="col-5">
                                            <%= f.submit "投稿する", class:"btn btn-outline-primary btn-block" %>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                        <br>
                    </div>
                  </div>
              </section>
          </main>
          <%= render 'shared/footer' %> 
      </div>
  </div>
</body>

app/views/photos/show.html.erb
<%= render 'shared/header' %>
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <h1 class="display-6 fw-bolder"><%= @photo.user.nickname%></h1>
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><%= image_tag @photo.snap, class: "card-img-top mb-5 mb-md-0" %></div>
            <div class="col-md-6">
                <% if @photo.user == current_user %>
                    <div class="row center-block text-center small mb-1">
                        <div class="col-lg-5">
                        <%=link_to "編集", edit_photo_path(@photo.id), class:"btn btn-outline-primary btn-block" %>
                        </div>
                        <div class="col-lg-5">
                        <%=link_to "削除", photo_path(@photo.id), method: :delete, class:"btn btn-outline-secondary btn-block" %>
                        </div>
                    </div>
                <% end %>
                <h1 class="display-6 fw-bolder"><%= @photo.title %></h1>
                <div class="fs-5 mb-5">
                    <% @photo_tags.each do |tag|%>
                      <span>#<%= tag.tag.name %></span>
                    <% end %>
                    <br>
                    ジャンル：<%= @photo.gender.name %>
                    <br>
                    Total金額：<%= @photo.price.name %>
                </div>
                <p class="lead"><%= @photo.description %></p>
            </div>
        </div>
    </div>
</section>
<!-- Related items section-->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Comments</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="card-body">
                <% if user_signed_in? %>
                    <%= form_with(model: [@photo, @comment], local: true) do |form| %>
                        <%= form.text_area :text, placeholder: "コメントを入力してください", class: "form-control", rows: "3" %>
                        <br>
                        <%= form.submit "コメントする", class:"btn btn-outline-primary" %>   
                    <% end %>
                <% else %>
                    <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
                    </strong>
                <% end %>
                <br>
                <% @comments.each do |comment| %>
                    <p>
                    <% unless comment.user.profile_image.blank?%>
                        <%= image_tag comment.user.profile_image, class: "rounded-circle", size: "50x50"%>
                    <% else %>
                         <%= image_tag "https://dummyimage.com/900x400/dee2e6/6c757d.jpg", class: "rounded-circle", size: "50x50"%>
                    <% end %>
                    <%= link_to comment.user.nickname, "/users/#{comment.user_id}", style: "text-decoration: none; color: black;", class: "fw-bold"%>
                    : <%= l comment.created_at %>
                    <% if comment.user == current_user %>
                    <%=link_to "削除", "/photos/#{comment.photo.id}/comments/#{comment.id}", method: :delete, class:"btn btn-outline-secondary" %>
                    <% end %>
                    </p>
                    <div class="ms-3", style="border-bottom: 1px solid #dee2e6;">
                        <%= comment.text %> 
                    </div>
                    <br>
                <% end %>
            </div>
        </div>
    </div>
</section>
<!-- Footer-->
<%= render 'shared/footer' %>